# Generated by Django 6.0 on 2026-01-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_booking_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthpackage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.healthpackage'),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='tests_included',
            field=models.TextField(),
        ),
    ]
