# Generated by Django 6.0 on 2026-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_healthpackage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
