# Generated by Django 6.0 on 2026-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_healthpackage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
