# Generated by Django 6.0.1 on 2026-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_healthpackage_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
