# Generated by Django 6.0.1 on 2026-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_mobileotp_resend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='HealthPackage',
        ),
    ]
